### ISSUE TITLE
Subs alphabetical order

### ISSUE THREAD

**Issue by ojsef39** [lo-cafe/winston#104]
Some subs are not alphabetically ordered.

![image](https://github.com/Kinark/winston/assets/43563019/530c06ad-cf5c-42f3-8bb3-bdffab76171a)
 
![image](https://github.com/Kinark/winston/assets/43563019/d3dccfcc-d285-44cf-8040-98187f0b3776)
https://discord.com/channels/1094807340903039048/1158762759601791036

**Comment by dvandersluis** [comment]
Not sure if this is related, but the search on the subs pane also is broken and returns random subs that don’t match the search.
