### ISSUE TITLE
Seeing “gif” as a comment instead of actual gif

### ISSUE THREAD

**Issue by ojsef39** [lo-cafe/winston#110]
![image](https://github.com/lo-cafe/winston/assets/43563019/5c8a85e6-6a46-48cd-8a52-4add98f0bfb2)

https://reddit.com/r/Wellthatsucks/comments/15x7vc8/my_covid_project_was_growing_a_pineapple_its_been/jx75ce8/
https://reddit.com/r/Wellthatsucks/comments/15x7vc8/my_covid_project_was_growing_a_pineapple_its_been/

https://discord.com/channels/1094807340903039048/1143389428409180232

**Comment by ggeor84** [comment]
why was this closed? This is still an issue

**Comment by ojsef39** [comment]
> why was this closed? This is still an issue

@ggeor84 #302 was closed because it was a duplicate of this issue
