### ISSUE TITLE
[FR] swipe to collapse comments.

### ISSUE THREAD

**Issue by frostplexx** [lo-cafe/winston#162]
Super happy we have custom gestures.  Was hoping if we could get a swipe gesture to collapse all comment thread. That was my most used feature with Apollo and if this feature because available I can finally uninstall the Reddit app fully.

**Comment by ojsef39** [comment]
related to: #collapse

**Comment by pankopan** [comment]
I recently added https://github.com/lo-cafe/winston/pull/350 which only acts on the comment the gesture is on. I think making it walk back up to the parent makes sense, what do you think?

**Comment by ojsef39** [comment]
> I recently added #350 which only acts on the comment the gesture is on.
Thanks for that :) But i just noticed, that it only works to hide the comment, you cant unhide with a swipe. You still have to press like the default to show the comment again.


> I think making it walk back up to the parent makes sense, what do you think?

Yes this would make it look way nicer :)
