### ISSUE TITLE
[FR] Jump to next group of comments button

### ISSUE THREAD

**Issue by Frostplexx** [lo-cafe/winston#169]
Available on Apollo and narwhal. Makes navigating comments a little easier.

Needs to be cherry picked from alpha, @ejbills

**Comment by MikeVensel** [comment]
I miss this so much from Apollo. Please add it. 🙏

**Comment by Languedoc5096** [comment]
Wholeheartedly agree. The current share/save/upvote/downvote button is way too large and intrusive on the comments page. This app at least needs the option to disable the current button and enable a comment jump button. This otherwise great app really suffers from not having this feature.

**Comment by pol-delta** [comment]
The lack of this feature is honestly the only thing keeping me from using Winston as a daily driver. Easiest way to massively improve usability of the app.
