### ISSUE TITLE
Smaller UI elements

### ISSUE THREAD

**Issue by BlueJeans7** [lo-cafe/winston#17]
Could you please add an option to slightly reduce the size of Comments/UI elements? Currently, they appear a bit too large.

**Comment by m3enzo** [comment]
I agree, the text is huge as well. Maybe an option to resize text as well.

**Comment by BlueJeans7** [comment]
Thanks for implementing UI element size. 

Please check for the below issues.

1. “Load X more” text doesn’t scale with comment size settings.
![IMG_5164](https://github.com/Kinark/winston/assets/24786247/f11d3fe1-89c1-4229-925b-d5aee78854a9)

2. Comment tree line gets broken in flat view. Please find attached screenshot with reference.
![IMG_5161](https://github.com/Kinark/winston/assets/24786247/452ea277-3f0f-4c05-b2ca-356432504a5d)

3. Default settings can be made as shown in the screenshot for best view.
![IMG_5162](https://github.com/Kinark/winston/assets/24786247/7b34fbe0-3bd5-4607-84d7-0a93bf56fc40)


![IMG_5163](https://github.com/Kinark/winston/assets/24786247/9ab1d102-1fe9-44b2-94cf-29c94f0d81a7)

Instead of providing detailed control over these settings, they can be categorized as very small, small, medium, large, and very large. This way, the user interface can be scaled accordingly.
