### ISSUE TITLE
[FR] Please add option to mute subreddits

### ISSUE THREAD

**Issue by Frostplexx** [lo-cafe/winston#173]
I can’t use this platform without muting subreddits anymore. I have to mute about 20 political subs, 10 lazy people who don’t want to contribute subs, and 5 anime subs.

**Comment by Frostplexx** [comment]
@Kinark Isn't this what "Filtered Subreddits" does?

**Comment by Kinark** [comment]
I think so, tbh idk what filtered subs do :D sorry
I'm not one of the ones who uses it :(
