### ISSUE TITLE
[FR] Make subs favoritable without subscribing to them

### ISSUE THREAD

**Issue by Frostplexx** [lo-cafe/winston#179]
see title

**Comment by iitzRichie** [comment]
Wouldn't this just be the Local Favorites feature? (which atm is bugged)

https://github.com/lo-cafe/winston/issues/99

**Comment by ojsef39** [comment]
> Wouldn't this just be the Local Favorites feature? (which atm is bugged: https://github.com/lo-cafe/winston/issues/99)

You're right, i'll close this. Thank you!
