### ISSUE TITLE
[Bug] not all sites open in safari

### ISSUE THREAD

**Issue by user858753257** [lo-cafe/winston#180]
As a user I want to open all URL links in safari . 

I have seen that some domains aren't opened there.

**Comment by ojsef39** [comment]
> I have seen that some domains aren't opened there.

Hi have you "Open links in Safari?" (Settings -> Behaviour) enabled and if so, could you please pay attention which domains are opened in the inapp browser anyway and report/post them here? :)

**Comment by F3000** [comment]
Here are some examples from posts in my home timeline (the links are mostly in comments) :

- https://slickdeals.net/share/iphone_app/fp/865786

- https://preview.redd.it/1n43q84h1srb1.png?width=1180&format=png&auto=webp&s=3c7164fb6f803b412a854325a2cf98519bc65512

- https://www.reddit.com/r/sysadmin/comments/d1ss5w/admin_refuses_to_upgrade_windows_7_and_server/

- https://en.wikipedia.org/wiki/Rusty_trombone

- https://www.bbc.co.uk/news/live/world-middle-east-67050350

- https://i.imgur.com/VeKmQVn
