### ISSUE TITLE
[Bug] App Icon change doesn’t work on iPad

### ISSUE THREAD

**Issue by user858753257** [lo-cafe/winston#185]
tested it with iPad mini 6 . iOS 17.0.2
Same build on iPhone went fine

Comments from Discord: 

Frostplexx — 01.10.2023 22:00
Works for me on iPad 7th gen iOS 17.0.2
regenerator — 03.10.2023 16:46
Worked ok for me .. 10th gen iPad iOS 17

 — 04.10.2023 00:17
tested it after restart . No way 😭
ojsef39 — 04.10.2023 09:47
soo, it works for you now as well? 🙂 
user858753257

 — 04.10.2023 17:26
no .  also after a device restart not
ojsef39 — 09.10.2023 12:09
does it work with the latest build? (144)
user858753257

 — gestern um 01:05 Uhr
no 😭
should we transfer the ticket also to github ?

**Comment by F3000** [comment]
@Frostplexx tested it today with my work iPad Air 5.Gen with iOS 17.0.3 

Here it works . 

So only iPad mini has this problem .

Would be good when somebody confirm this

**Comment by Frostplexx** [comment]
From a few other reports on Discord it seems that this isn't iPad specific, but its very hard to reproduce.
