### ISSUE TITLE
[Bug]  App crashes when open random subreddits

### ISSUE THREAD

**Issue by user858753257** [lo-cafe/winston#194]
Some subreddits crashes some not . Didn't find a behavior right now .

https://github.com/lo-cafe/winston/assets/8161283/f2548985-0d77-4837-9560-befbf2d1ba71

**Comment by ojsef39** [comment]
related to #189

**Comment by Frostplexx** [comment]
Does this still happen @user858753257?

**Comment by user858753257** [comment]
@Frostplexx at the moment no
