### ISSUE TITLE
[FR] Allow to set the font size in Posts Feed view

### ISSUE THREAD

**Issue by MindfulWolfPack** [lo-cafe/winston#198]
Prior to the implementation of themes, Winston allowed to change the font size of the text on the Posts Feed view. 
But with themes this is no longer possible and the text is using the default iOS (small) font size. 
Is it possible to bring back the ability to set a specific font size there?

Thank you!

![image](https://github.com/lo-cafe/winston/assets/6178252/0cfdb651-3b60-4011-a450-faf1659f0989)

**Comment by ojsef39** [comment]
Hi you can change all font sizes here :) 

If that doesn't work for you, feel free to reopen this issue.

![image](https://github.com/lo-cafe/winston/assets/43563019/e19597ac-b92e-4228-b49b-ca4cc8ba18e0)

**Comment by MindfulWolfPack** [comment]
Hi @ojsef39 sadly this only changes the fonts in the individual "Post page" and not in the "Posts Feed view", which is the list of posts in "Home", "Popular", "All", Subreddit etc.
We need similar settings inside the Settings --> Appearance --> Themes --> Theme --> "Posts feed" settings. It is missing there. Thanks!

**Comment by MindfulWolfPack** [comment]
@ojsef39 can you please reopen this issue for me (see comment above)? I don't see a way to reopen this issue.

**Comment by ojsef39** [comment]
> Hi @ojsef39 sadly this only changes the fonts in the individual "Post page" and not in the "Posts Feed view", which is the list of posts in "Home", "Popular", "All", Subreddit etc.

Sorry my bad i sent the screenshot from the wrong section, here it is :) 

![image](https://github.com/lo-cafe/winston/assets/43563019/b4546ea4-95a5-457c-be5e-039deba39b91)

**Comment by MindfulWolfPack** [comment]
@ojsef39 Thank you! so it is under "Posts links" got it. That is what I was looking for.
