### ISSUE TITLE
[BUG] Random subreddit appeared «4» 

### ISSUE THREAD

**Issue by hlillebjerka** [lo-cafe/winston#204]
**Describe the bug**
Opened winston, and in my overview of subreddits, there was a subreddit called “4”
When I enter it, it seems like a collection of several subreddits. Example is the first one being the global offensive subreddit. 

**To Reproduce**
No clue

**Expected behavior**

**Screenshots**
![IMG_3984](https://github.com/lo-cafe/winston/assets/5364182/ec80a79d-97e7-47dc-b156-b8b7375ffd4e)
![IMG_3983](https://github.com/lo-cafe/winston/assets/5364182/d3337806-dada-4738-a4e3-25785d4a99d5)
![IMG_3982](https://github.com/lo-cafe/winston/assets/5364182/5c04490f-4f1a-4543-891f-34868f595005)

**Winston (please complete the following information):**
 - Version Beta v1.0
 - Build Number 144

**Device (please complete the following information):**
 - Device: iPhone 14 pro
 - OS: iOS 17.0.3

**Additional context**

**Comment by ojsef39** [comment]
Hi thanks for you report!

Could you add an additional screenshot from the subredditlist (where the "4" is shown)

and after that try clearing the cache and please give feedback if that resolved your issue. thanks! :)

**Comment by ojsef39** [comment]
also it would be nice to know if you had any multis or subreddits, with one or more of those subreddits listed. maybe its a weird caching bug.

**Comment by Frostplexx** [comment]
@hlillebjerka does this still happen to you?
