### ISSUE TITLE
[FR] Make read/unread post indication more clear

### ISSUE THREAD

**Issue by jacopo-j** [lo-cafe/winston#221]
Hello. Winston uses a green dot on the top right of each post's "card" to indicate that the post hasn't been read. However, the green dot is not very prominent, and in some cases it can be pretty hard to see–especially when using the light theme. Example:

![image](https://github.com/lo-cafe/winston/assets/9914547/7c72f7e6-7940-4f3a-a7a9-2e69499c5441)

I would suggest to make the read/unread post indication easier to see or, alternatively, to signal that a post has been read by making the title text greyed out, as other applications (e.g. Apollo, Dystopia) do.

**Comment by iitzRichie** [comment]
If you go into _Settings_ > _Appearance_ and edit the theme, in the _Post Links_ tab you can scroll to the bottom and there's something called _Unseen Type_ which gives you an option to have the _Dot_ or _Fade_.

**Comment by jacopo-j** [comment]
Thank you! I missed that setting. Hopefully this will be useful to other people searching in the future.
