### ISSUE TITLE
Clicking on a collapsed reply takes you to the user page

### ISSUE THREAD

**Issue by maurymarkowitz** [lo-cafe/winston#23]
If you collapse a reply thread, clicking on the collapsed thread will always hit the user's name, and take you to the user's page.

This is confusing, because the action for collapsing the thread is to click-n-hold on the message, but once collapsed this action does not un-collapse the thread, and a single click takes you to an entirely different page.

**Comment by ojsef39** [comment]
Hi @maurymarkowitz, is this still the case for you?

Just tried it out, and it works like it should.
(Also, die gesture is not click-n-hold, it's just clicking)
