### ISSUE TITLE
[BUG] Don’t open links in safari from post list view

### ISSUE THREAD

**Issue by alienator88** [lo-cafe/winston#237]
**Describe the bug**
Currently if you have `open links in safari` disabled, the links still open in safari from the post list view. Clicking on posts sometimes, you accidentally click the link and it opens the browser. With the setting off I would expect all links to open in the internal browser. Or have another setting to control the post list view links.

**To Reproduce**
1. Disable opening links in safari from settings
2. Go to main post list view
3. Tap link on any post
4. Notice it still opens in default browser

**Expected behavior**
With the setting disabled, all links in the app should open in the built-in browser to have consistency with the setting.

**Screenshots**
![image](https://github.com/lo-cafe/winston/assets/6263626/5e0bb1b7-3dfb-4a2f-9228-be8b3ae793e0)
![image](https://github.com/lo-cafe/winston/assets/6263626/a62ae73d-3844-4a0d-b01f-b296071b8a2b)

**Winston (please complete the following information):**
 - Version 1.0.0
 - Build Number 162

**Device (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 17.2 Dev Beta

**Comment by Frostplexx** [comment]
Does this still happen @alienator88?

**Comment by alienator88** [comment]
Just tested on build 204 and it does

**Comment by ojsef39** [comment]
is fixed
