### ISSUE TITLE
Share, saved posts and new posts

### ISSUE THREAD

**Issue by ribena75** [lo-cafe/winston#245]
**love the app**
- the share function doesn’t work, nothing happens when I press it
- saved posts are not visible under saved (nothing actually happens when clicking on saved)
- there is no option to create a new post!

**Comment by ojsef39** [comment]
Closing this issue because those issues are known and there are separate issues for them.

**Comment by ojsef39** [comment]
#81, #89 and for creating posts is no desperate ticket but we are aware of it :)
