### ISSUE TITLE
[BUG] GIFs not shown correctly

### ISSUE THREAD

**Issue by Jepl4r** [lo-cafe/winston#267]
GIFs don't show in the feed or when opening the post. They're shown only when I directly open them.
Happening on both of my iPhone 13 Pro Max and 15 Pro Max

Winston version is 1.0.0 with build number 162
iOS version is 17.1.1

![image](https://github.com/lo-cafe/winston/assets/115885800/e81a4385-f62e-4856-920b-72b5ba6f5016)

**Comment by ojsef39** [comment]
i think this could be related to #100

**Comment by Jepl4r** [comment]
@ojsef39 I never had that bug, but I don't think it's the same thing that's happening now. The bug started after I updated to the latest version on the 13. On the 15 I installed the latest version without updating it cause I got the phone last week on Saturday.

**Comment by ojsef39** [comment]
> @ojsef39 I never had that bug, but I don't think it's the same thing that's happening now. The bug started after I updated to the latest version on the 13. On the 15 I installed the latest version without updating it cause I got the phone last week on Saturday.

mhmm interesting, thanks for the feedback tho, i'm sure that will help :)
