### ISSUE TITLE
[Bug] App can't load "Me" section

### ISSUE THREAD

**Issue by user858753257** [lo-cafe/winston#294]
Beta 1.1.0
Build 204 

Pressing on "Me" Tab doesent load any content . 
Rest of the app is working fine

**Comment by ThisBlackCat** [comment]
I get the same bug. I've tried other people's suggestions of clearing cache, updated the Reddit redirect. No luck.

**Comment by ojsef39** [comment]
Is fixed (maybe hotfix to alpha gets released soon)

**Comment by kibabyte** [comment]
By "alpha" you mean what exactly? Would be super great if TestFlight gets the updated build quickly, it's broken for me for about a week, thx.

**Comment by ojsef39** [comment]
> By "alpha" you mean what exactly? Would be super great if TestFlight gets the updated build quickly, it's broken for me for about a week, thx.

By alpha, I mean our internal testing "stage" or testing build. I'm really sorry I can't give you a time, when an update will go live on TestFlight, but I think it's going to be pretty soon 🤞
