### ISSUE TITLE
[BUG] Markdown tables aren't formatted

### ISSUE THREAD

**Issue by pankopan** [lo-cafe/winston#320]
**Describe the bug**
Tables are not supported. Known issue from https://github.com/christianselig/Markdownosaur?

**To Reproduce**
1. View a post or comment with a table

**Expected behavior**
Example from native iOS reddit app. Shows header/rows and scrolls off the page.
![IMG_033660BB8BEF-1](https://github.com/lo-cafe/winston/assets/152220723/abf1a6f5-a414-4c29-ba29-41b296b7f9dd)

**Screenshots**
![Simulator Screenshot - iPhone 15 Pro - 2023-11-30 at 22 03 55](https://github.com/lo-cafe/winston/assets/152220723/7b4a77ba-e36a-4b3a-8a76-f4f5f51c7b1d)

**Winston (please complete the following information):**
 - Version [e.g. Beta v1.0]
 - Build Number [e.g. 144]

**Device (please complete the following information):**
 - Device: [e.g. iPhone 15]
 - OS: [e.g. iOS 17.0]

**Additional context**

**Comment by ojsef39** [comment]
not fixed according to: https://discord.com/channels/1094807340903039048/1144063085951320094/1195263373491843133

**Comment by ojsef39** [comment]
![image](https://github.com/lo-cafe/winston/assets/43563019/a265ac2e-477d-4f9d-8aa9-f90d91abddd6)
![image](https://github.com/lo-cafe/winston/assets/43563019/03628109-6dd2-4ed8-bc2b-b03251cfdbc0)
