### ISSUE TITLE
[BUG] Multiple posts are being marked as read simultaneously

### ISSUE THREAD

**Issue by valberjr** [lo-cafe/winston#331]
**Describe the bug**

When enter a subreddit, I have for example 5 unread posts. When access a specific post and then go back to the subreddit's main page, the 4 posts below the read one are being marked as read automatically.

**To Reproduce**

1. Go to /r/nextdns, for example
2. Click on any unread posts, preferably with some unread ones below the one you're clicking.
3. Return to /r/nextdns
4. The ones below now are marked as read too.

**Expected behavior**

Only the post clicked to read should be marked as read when return to /r/nextdns

**Screenshots**

1 - All posts are unread.

![IMG_0911](https://github.com/lo-cafe/winston/assets/66678781/2a52fbbc-b395-4389-83ac-ed9bdbbe678c)

2 - I entered the first post

![IMG_0912](https://github.com/lo-cafe/winston/assets/66678781/c165b90e-ff73-4c1c-a811-7ea0a0244e28)

3 - Returned to /r/nextjs, and now the posts below are also marked as read, even though I haven't read them

![IMG_0913](https://github.com/lo-cafe/winston/assets/66678781/2935d984-4230-4f2a-b644-e7dd08d28e5a)

4 - Here's a video

https://github.com/lo-cafe/winston/assets/66678781/6f2136f6-cbc3-4f45-9b84-4299eb2f2deb

5 - JFYI

I created a theme in options and then configured the "posts links > card > Unseen type" as Fade, but the same still occurs with dot.

![IMG_0914](https://github.com/lo-cafe/winston/assets/66678781/b477d144-1c72-4441-8b42-3efbaea73a15)

**Winston (please complete the following information):**
 - Version 1.1.0
 - Build Number 228

**Device (please complete the following information):**
 - Device: iPhone14
 - OS: iOS 17.1.2

**Additional context**

**Comment by ojsef39** [comment]
i think that’s a read on scroll issue

**Comment by valberjr** [comment]
Indeed, that’s a read on scroll issue. I disabled it here, and it worked as expected.

**Comment by ojsef39** [comment]
> Indeed, that’s a read on scroll issue. I disabled it here, and it worked as expected.

perfect, yeah im using the same workaround atm. hope this gets fixed soon :)
