### ISSUE TITLE
[BUG] Misaligned UI Elements w/ Show Author In Combination w/ Compact Mode

### ISSUE THREAD

**Issue by iitzRichie** [lo-cafe/winston#342]
**Describe the bug**
When "Show Author" is disabled in combination with Compact Mode, some posts have their elements misaligned. For some reason the posts that I have in my Saved are the worst of it. To sort of fix it I can enable Show Author and then just make the Author color blend in with my background to sort of make the Author invisible, but then that makes the subreddit tag look weird.

**To Reproduce**
1. Enable Compact Mode in Appearance
2. Disable Show Author in Appearance
3. Unfortunately I can't point to a direct place where this is happening because it's already wonky as is.

**Expected behavior**
UI elements properly aligned.

**Screenshots**
![image](https://github.com/lo-cafe/winston/assets/50350344/78768943-be7f-4947-aa3f-f26eec849d8c)

**Winston:**
 - Version: 1.1.0
 - Build Number: 256

**Device:**
 - Device: iPhone 15
 - OS: iOS 17.2

**Additional context**
_Note: I'm using the Alpha build, but I can't remember if it was like this on Beta or if it's just an Alpha thing_

**Comment by iitzRichie** [comment]
[12/21/23: This is the worst I've seen of it](https://github.com/lo-cafe/winston/assets/50350344/e6eaf456-8649-4e58-868c-934a0023d880)

**Comment by ojsef39** [comment]
i think it's theme related, i had a similar issue with catpuccin theme. when you disable it, it should be working again.
![image](https://github.com/lo-cafe/winston/assets/43563019/f04d717c-163f-4f00-9dd2-bb353663b736)

**Comment by iitzRichie** [comment]
> i think it's theme related, i had a similar issue with catpuccin theme. when you disable it, it should be working again. <img alt="image" width="315" src="https://private-user-images.githubusercontent.com/43563019/293416133-99a0c291-66f6-49ea-88de-5d8a20974e42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NDYzNzQsIm5iZiI6MTcwMzk0NjA3NCwicGF0aCI6Ii80MzU2MzAxOS8yOTM0MTYxMzMtOTlhMGMyOTEtNjZmNi00OWVhLTg4ZGUtNWQ4YTIwOTc0ZTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDE0MjExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMzViZmE4NzU1YTg3M2QyZTYzNjgyNWEzZjNjYTVjNmQ2MWRjM2YxMGYwNDY2ZThlODc5ZTQ1ODFmYTk3NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cpmZYUhUTlSApGctQ7DFEH2m0xJuMRHru82MKT42SY4">

I forgot who it was in the Discord, but we found out that it's related to disabling "Show Author" in combination with using Compact Mode, in which case enabling "Show Author" puts it back to how it normally is.

**Comment by iitzRichie** [comment]
Possibly fixed in 1.1.2 (319)
