### ISSUE TITLE
[FR] Winston Everywhere Automatically Activated

### ISSUE THREAD

**Issue by CyberFoxTech** [lo-cafe/winston#356]
**Is your feature request related to a problem? Please describe.**

Technically not a problem. Winston’s Safari extension currently requires the user to click “Open in Winston” on the banner every time they want to transfer the link.

**Describe the solution you'd like**

Would just love if Winston Everywhere would activate automatically instead of requiring me to click “Open in Winston” every time. This was my all time favorite feature of Apollo and the only thing Winston is missing for me. 

**Describe alternatives you've considered**

N/A

**Additional context**
Feature of a few Reddit clients. Apollo previously and I believe Narwhal 2 does this.

**Comment by Frostplexx** [comment]
This is actually a bug that occurs on all search engines that aren't google. If you search for a reddit link on google it directly opens in Winston.
