### ISSUE TITLE
[FR] Support iOS 15

### ISSUE THREAD

**Issue by dtantono** [lo-cafe/winston#357]
**Is your feature request related to a problem? Please describe.**
it does not start on IOS 15

**Describe the solution you'd like**
many functional iPhones cannot upgrade to latest iOS

**Describe alternatives you've considered**
use another Reddit app

**Additional context**
it will be useful if Winston lower the iOS requirement

**Comment by ojsef39** [comment]
Hi, im sorry but we won't lower the iOS requirements. Afaik we are now at 16.4 as the minimum and it wouldn't make much sense to lower the requirements.

Thanks nonetheless for your time creating this issue :) Have nice holidays and a great start into the next year :)

**Comment by Frostplexx** [comment]
To add to @ojsef39 response: We're using features that are only available on iOS 16.4 and later. Therefore we wont lower the minimum iOS version
