### ISSUE TITLE
[BUG] Reddit error during authentication

### ISSUE THREAD

**Issue by PrMinisterGR** [lo-cafe/winston#370]
Hello and thanks for the effort with the app!

I have created a Reddit Web App key, as it is the only one showing me an ID and Secret, but no matter what, when I try to login from the app, the browser opens and Reddit gives me the following error:

There was an error trying to connect with your reddit account

You got here because a third-party application wanted to authorize connecting with your reddit account. However an unknown error occurred, please see details below. Please try refreshing the page or coming back later.
Error: Invalid request to Oauth API

It’s also not clear anywhere what we’re supposed to be using as a redirect URI.

Am I doing something wrong or is this a real issue? Thank you!

**Comment by mshaban** [comment]
Somehow the onboarding doesn't show up after installing the app for the first time, but if you go through the code there is an onboarding where it specifies what values to use for the direct url.

here are they:
    - App Name: Winston
    - Desc: Whatever
    - about url: https://lo.cafe
    - redirect url: https://app.winston.cafe/auth-success
    
Make sure app name, about and redirect urls are exactly like this.

**Comment by PrMinisterGR** [comment]
Thank you very much for this! Everything is working fine now!On 1. Jan 2024, at 15:45, Shaban ***@***.***> wrote:﻿
Somehow the onboarding doesn't show up after installing the app for the first time, but if you go through the code there is an onboarding where it specifies what values to use for the direct url.
here are they:
- App Name: Winston
- Desc: Whatever
- about url: https://lo.cafe
- redirect url: https://app.winston.cafe/auth-success
Make sure app name, about and redirect urls are exactly like this.
