### ISSUE TITLE
[BUG] it shows nothing on the home feed

### ISSUE THREAD

**Issue by dnet890** [lo-cafe/winston#380]
**Describe the bug**

**To Reproduce**
1. Go to Settings
2. Click on Credentials
3. insert App ID and APP Secret
4. it shows nothing

**Expected behavior**
it should shows the posts

**Screenshots**

**Winston (please complete the following information):**
1.1.1

**Device (please complete the following information):**
iOS 16.4
![IMG_0046-2](https://github.com/lo-cafe/winston/assets/29157187/a05f9b90-34aa-4d4f-b62d-704f1f6d16d9)
![IMG_0047](https://github.com/lo-cafe/winston/assets/29157187/5b8e0995-cee7-43d1-b4d6-d083f57503d4)

**Additional context**

**Comment by ojsef39** [comment]
@dtantono is this still happening? i think that's fixed now :)
