### ISSUE TITLE
Support multiple accounts

### ISSUE THREAD

**Issue by ebertn** [lo-cafe/winston#39]
The biggest thing keeping me from using winston right now is the lack of support for multiple accounts/account switching.

A great stretch feature for this would be an option to have settings (all settings) on a per account basis. 

For example, on one account I may want compact posts and on another I may want large posts.

**Comment by ebertn** [comment]
I’d be open to developing this myself if you’re accepting PRs.

**Comment by ojsef39** [comment]
> I’d be open to developing this myself if you’re accepting PRs.

I think Kinark is already working on that :) But you're always happy to help out with PRs:)

![image](https://github.com/Kinark/winston/assets/43563019/f7176e4d-cd86-4fe1-a831-5b0a2045d016)
