### ISSUE TITLE
Changelog in discord?

### ISSUE THREAD

**Issue by LeviSnoot** [lo-cafe/winston#418]
Why? Discord is not a wiki, it's a closed off community hub. Don't lock important information like changelogs behind it please. Thanks.

**Comment by ojsef39** [comment]
Hi @LeviSnoot, you can see the changelogs in Testflight and in-app the newest changes under settings -> what’s new

**Comment by LeviSnoot** [comment]
I'm not in the Testflight nor can I access the "What's New" option.

![image](https://github.com/lo-cafe/winston/assets/13402525/d22d4c32-b0cc-4ca5-ae17-ab8cd4fd7678)

**Comment by Frostplexx** [comment]
@LeviSnoot I've updated the release page with the changelog.
