### ISSUE TITLE
[BUG] Letterboxing when rotated to landscape mode

### ISSUE THREAD

**Issue by Marcus5408** [lo-cafe/winston#419]
**Describe the bug**
When rotating an iPhone to landscape mode, the UI correctly expands to fill the view. However, letterboxing gets added to the left and right sides of the screen.

**To Reproduce**
1. Go to anywhere in Winston
2. Disable Portrait Orientation Lock if it is on
3. Rotate the device to landscape mode
4. See erroneous behavior

**Expected behavior**
The UI adapts to landscape mode and works perfectly with no letterboxing

**Screenshots**
![image](https://github.com/lo-cafe/winston/assets/46655509/52a05aed-ccf1-4a33-95f3-a876aa7e4f3f)

**Winston:**
 - Version: Beta v1.1.2
 - Build Number: 324

**Device:**
 - Device: iPhone 14 Plus
 - OS: iOS 17.2.1

**Comment by ojsef39** [comment]
(rotation is disabled for now)

**Comment by ojsef39** [comment]
fixed in alpha, should be in next release :)
