### ISSUE TITLE
[FR] Allow pasting acquired token into app instead of relying on deeplinks

### ISSUE THREAD

**Issue by notmarek** [lo-cafe/winston#507]
**Is your feature request related to a problem? Please describe.**
I can't use Winston inside live container since it doesnt support deeplinks

**Describe the solution you'd like**
Add a way to paste the user access/ refresh tokens manually 
 
**Describe alternatives you've considered**
Joining TestFlight: full, installing as a normal app thought SideStore: 3 app limit is annoying that's why i use live container, buying a certificate: needlessly expensive even trough resellers for my use case

**Additional context**
N/A

**Comment by ojsef39** [comment]
you can use the advanced setup for manually inputting the token

**Comment by notmarek** [comment]
That only works for the app token.. I'm trying to authorize the app, if
there's a way to do that i haven't found it yet

**Comment by ojsef39** [comment]
i see, sorry forgot about that.

Yeah sorry there isn't really a way to work around this atm

**Comment by notmarek** [comment]
No problem, thanks for letting me know

**Comment by ojsef39** [comment]
No worries, if there is a change in the future which allows us to do that i'll try to remember and update this :)
