### ISSUE TITLE
[BUG] Cannot add repository to AltStore (World) 1.7

### ISSUE THREAD

**Issue by otherguy** [lo-cafe/winston#528]
**Describe the bug**
The URL https://raw.githubusercontent.com/lo-cafe/winston-altstore/main/apps.json is valid JSON but it cannot be added to the current version of AltStore.

**To Reproduce**
Click the `Add to AltStore` link on the GitHub repository README / main page.

**Screenshots**
![Screenshot 2024-08-19 at 10 52 17](https://github.com/user-attachments/assets/7c1eb136-f753-4604-b207-5843aef0f8b6)

**Device (please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: iOS 17.6.1
 - AltStore (World) 1.7

**Comment by otherguy** [comment]
Never mind :) I had the wrong version of AltStore (World) installed.

**Comment by aguilaair** [comment]
hey! how did you fix this?

**Comment by ghost** [comment]
Also facing the same issue

**Comment by aguilaair** [comment]
@fazzer4x i just downloaded the ipa and installed it that way for the time being

**Comment by otherguy** [comment]
You need altstore world beta, for which you need to be a patreon subscriber.

I had the non-beta version installed and thought that was enough.

**Comment by aguilaair** [comment]
Why do you need the beta?

**Comment by otherguy** [comment]
Afaik you need the beta to add custom sources. 

Now it works just fine for me!

**Comment by ghost** [comment]
Actually, I can add custom sources to the alt store. However I'm facing following issue once I try and add the above mentioned url: 
<img width="414" alt="image" src="https://github.com/user-attachments/assets/0b7bd190-a0c4-4325-970a-464b43ce4af7">

**Comment by otherguy** [comment]
@enviousjag yeah that's exactly what I meant. Non-beta Altstore World only takes notarized sources. This source is **not** notarized and can therefore **only** be added to Altstore World _Beta_, which requires you to be a Patreon subscriber.

**Comment by ghost** [comment]
@otherguy now I understand. Thanks for clarifying.
