### ISSUE TITLE
[FR]Use at the app LiveContainer

### ISSUE THREAD

**Issue by KH0000001** [lo-cafe/winston#543]
**Is your feature request related to a problem? Please describe.**
Thank you for developping this app. I want to use winston on LiveContainer. I couldn’t  be complete api setting. Url is showing success.

**Describe the solution you'd like**
To use copy and paste url. Maybe it’s a solution ex.. 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by ojsef39** [comment]
Hey unfortunately this is not possible because those containers don’t share the same local url. so the auth callback does not suceed and we don’t really see a way atm on how we can fix this

**Comment by ojsef39** [comment]
#507

**Comment by KH0000001** [comment]
Thanks. I hope add the copy paste feature in the future. And I foeget to search before issues. Thank you for your support.

**Comment by ojsef39** [comment]
No worries :)
I forgot to search before too and only now saw that actually there is a PR open for this
#538

**Comment by Impure2411** [comment]
You can authorize it by following these steps below
https://github.com/khanhduytran0/LiveContainer/issues/242#issuecomment-2567079335
