### ISSUE TITLE
Add iCloud sync for settings / API key

### ISSUE THREAD

**Issue by Frostplexx** [lo-cafe/winston#98]
Synchronize API Keys and UserDefaults Settings using iCloud. I create a PR draft #97 which already implements syncing the API keys.
For the other settings we need to wait until https://github.com/sindresorhus/Defaults/pull/136 is merged into the library we're using.

**Comment by F3000** [comment]
Add possibility to sync "posts in Postbox" 
requested by user Richi: 

https://discord.com/channels/1094807340903039048/1123388195732721745/1161070198225383524
